In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("E:\\College_Backup\\BTech_Internship\\Persistent_Project\\Dataset-Pipeline\\NoCodeDatasetPreprocessing\\sample_datasets\\diabetes.csv")
df.head()

,date,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,dirtybool,BMI,DiabetesPedigreeFunction,Age,textIp1,textIp2,Outcome
0,8/13/2026,6,NaN,72.0,35.0,0.0,TRUE,33.6,0.627,50.0,Hello,HELLO,1.0
1,8/14/2026,1,NaN,66.0,29.0,NaN,TRUE,26.6,0.351,31.0,hello,HELLO,0.0
2,8/15/2026,8,NaN,40000.0,0.0,NaN,TRUE,23.3,0.672,NaN,HelLLOO,HELLLOO,1.0
3,8/16/2026,1,NaN,66.0,23.0,NaN,0,28.1,0.167,NaN,hi,HI,0.0
4,8/17/2026,0,NaN,40.0,985000.0,NaN,1,43.1,2.288,NaN,HHII,HHII,1.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 789 entries, 0 to 788
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      789 non-null    object
 1   Pregnancies               789 non-null    int64
 2   Glucose                   773 non-null    object
 3   BloodPressure             775 non-null    float64
 4   SkinThickness             782 non-null    float64
 5   Insulin                   772 non-null    float64
 6   dirtybool                 789 non-null    object
 7   BMI                       778 non-null    float64
 8   DiabetesPedigreeFunction  780 non-null    float64
 9   Age                       772 non-null    float64
 10  textIp1                   770 non-null    object
 11  textIp2                   768 non-null    object
 12  Outcome                   785 non-null    float64
dtypes: float64(7), int64(1), object(5)
memory usage: 80.3+ KB

In [11]:
df.describe()

,Pregnancies,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,789.000000,775.000000,782.000000,772.000000,778.000000,780.000000,772.000000,785.000000
mean,3.742712,118.789677,1279.468031,76.817358,32.308226,0.473705,33.177461,0.368153
std,3.381566,1434.596570,35222.820054,113.889935,8.035831,0.327341,11.582372,0.482611
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,62.000000,0.000000,0.000000,27.400000,0.245000,24.000000,0.000000
50%,3.000000,70.000000,22.000000,0.000000,32.400000,0.381500,29.000000,0.000000
75%,6.000000,80.000000,32.000000,125.000000,36.975000,0.630000,40.000000,1.000000
max,17.000000,40000.000000,985000.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [12]:
df.isna().sum()

date                         0
Pregnancies                  0
Glucose                     16
BloodPressure               14
SkinThickness                7
Insulin                     17
dirtybool                    0
BMI                         11
DiabetesPedigreeFunction     9
Age                         17
textIp1                     19
textIp2                     21
Outcome                      4
dtype: int64

In [13]:
df.value_counts()

date       Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  dirtybool  BMI   DiabetesPedigreeFunction  Age   textIp1  textIp2  Outcome
9/19/2028  0            145      0.0            0.0            0.0      FALSE      44.2  0.630                     31.0  Hello    HELLO    1.0        21
9/9/2028   1            106      76.0           0.0            0.0      TRUE       37.5  0.197                     26.0  HelLLOO  HELLLOO  0.0         1
9/4/2026   7            196      90.0           0.0            0.0      TRUE       39.8  0.451                     41.0  HHII     HHII     1.0         1
1/11/2027  4            114      65.0           0.0            0.0      TRUE       21.9  0.432                     37.0  hello    HELLO    0.0         1
1/11/2028  9            145      88.0           34.0           165.0    TRUE       30.3  0.771                     53.0  Hello    HELLO    1.0         1
                                                                                                                                                      ..
9/8/2026   7            147      76.0           0.0            0.0      TRUE       39.4  0.257                     43.0  HelLLOO  HELLLOO  1.0         1
9/8/2028   0            123      72.0           0.0            0.0      TRUE       36.3  0.258                     52.0  hello    HELLO    1.0         1
9/9/2026   1            97       66.0           15.0           140.0    TRUE       23.2  0.487                     22.0  hi       HI       0.0         1
9/9/2027   1            131      64.0           14.0           415.0    TRUE       23.7  0.389                     21.0  HelLLOO  HELLLOO  0.0         1
9/30/2027  1            143      74.0           22.0           61.0     TRUE       26.2  0.256                     21.0  hii      HII      0.0         1
Name: count, Length: 658, dtype: int64